language: ruby
rvm:
- 2.1

install: gem install html-proofer
script: jekyll serve --baseurl "" --detach && htmlproofer ./_site --disable-external

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true JEKYLL_ENV=production
