# Site settings

url: "https://evetion.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /
force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Maarten Pronk"
title: "evetion.nl"
description: "Blog and website of Maarten Pronk, blogging mainly for fun."
keywords: "pronk, maarten, personal, gis"
favicon: "/img/favicon-map.ico"

################
# Header layout #
################

black-favicon: "/img/favicon-mapsico"
background-img: "../img/arch_bg_small.png"

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text

me-img: "/img/me.jpg"

color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False
syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/tudelft.png"
    date: "September 2008 - June 2012"
    description: "BSc Architecture, Urbanism and Building Sciences"
  - image: "/img/timeline/tudelft.png"
    date: "September 2013 - June 2015"
    description: "MSc Geomatics, graduating in the <a href='https://3d.bk.tudelft.nl/'>3d geoinformation research group</a>."
  - image: "/img/timeline/deltares.png"
    date: "September 2015 - Today"
    description: "Working at <a href='https://www.deltares.nl/en/'>Deltares</a> as a researcher and advisor, working on open source <a href='https://github.com/openearth'>projects</a>."

# First image of the Timeline

timeline-img: "/img/me.jpg"

###########
# Contact #
###########

email: "contact@evetion.nl"

#########
# Repos #
#########

github-info:
  handle: "evetion"
  repo-desc-char-limit: 50
  repo-display-limit: 2

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/evetion"
  - title: "linkedin"
    url: "https://nl.linkedin.com/in/maarten-pronk-8b707040"
  - title: book
    url: "http://repository.tudelft.nl/view/ir/uuid%3Ada6b7329-f45b-4560-8374-bb522e78121f/"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/star.gif"

################################################################################

# Sections shown in the index page

pages_list:
  About: 'about'
  Thesis: 'thesis'
  Projects: 'latest-post'
  Timeline: 'timeline'
  Repos: 'repos'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
  # - jekyll-scholar
